In [1]:
import cv2
import torch
import torchvision
from PIL import Image
torch.device = "cuda"

In [2]:
img = cv2.imread("1.jpg")


In [29]:
cv2.imshow("13",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:

rgbimg = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
imgtensor = torch.IntTensor(rgbimg)
print(imgtensor.shape)
print(imgtensor.ndim)

torch.Size([640, 640, 3])
3


In [3]:
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda_version)
[x for x in range(10)]

False
0
None


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
t1 = torch.tensor([x for x in range(1,23,7)],dtype=torch.float16)
t2 = torch.tensor([1047483648,1047483628,1047483638,12],dtype=torch.int32)
t3 = torch.tensor([x for x in range(4,41,12)],dtype=torch.int32)
print(t1)
print(t2)
print(t3)
print(t1 * t2)
print(t1 * t3)


tensor([ 1.,  8., 15., 22.], dtype=torch.float16)
tensor([1047483648, 1047483628, 1047483638,         12], dtype=torch.int32)
tensor([ 4, 16, 28, 40], dtype=torch.int32)
tensor([ inf,  inf,  inf, 264.], dtype=torch.float16)
tensor([  4., 128., 420., 880.], dtype=torch.float16)


In [9]:
rantense = torch.mul(torch.rand(size=(3,10,10)),255).type(dtype=torch.int32)
transform = Tvt.ToPILImage()
tenseimg = transform(rantense)
tenseimg.show()
rantense

NameError: name 'T' is not defined